name = "github-oauth-login"
main = "src/worker.ts"
#type = "javascript"
account_id = "bc2043c616d427139c181d21fc6274c7"
compatibility_date = "2025-01-21"
workers_dev = true
route = ""
zone_id = ""

[ vars ]
TEST = "test var"
# Development variables here
# CLIENT_ID = "your-dev-client-id"

# Production secrets should be set in the Cloudflare dashboard
# [secrets]
# CLIENT_ID
# CLIENT_SECRET
